config/routes.rb
SampleApp::Application.routes.draw do
  

  devise_for :admins

  resources :cytostatic_drug_given_bone_marrows

  devise_for :users
  match '/patients', to: 'patients#destroy', via: 'delete'
  resources :patients
  match '/patients/:id/edit_remission', to: 'patients#edit_remission', via: 'get'

  resources :bone_marrow_transplantations
  resources :chemo_therapies
  resources :cytostatic_drug_givens
  resources :cytostatic_drug_given_bone_marrows
  

  resources :users
  resources :journals
  match '/journal/:id/edit_relapse(.:format)', to: 'journal#edit_relapse', via: 'get'
  resources :surgeries

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/form/setcountry', to: 'form#setcountry', via: 'put'

  match '/form/get_journals', to: 'form#get_journals', via: 'get'
  match '/form/:id(:format)', to: 'form#show', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @progress = (Patient.where(is_done: true).count.to_f / Patient.all.count.to_f) * 100
  end


  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
  <% if user_signed_in? %>
<div ng-app="myApp">
  <div ng-controller="MyCtrl">
    <div class="row-fluid">
      <div class="span6" align="center">
        <h2 style="text-align:center">Select an ALiCCS-study number</h2>
        <input align="center" placeholder="Search..." ng-model="filterOptions.filterText" style="width:200px;"/>
        <div class="gridStyle" ng-grid="gridOptions"></div>
        Total: {{myDataNotDone.length}}
        <% if current_user.admin %>
        <h4>
          Create a new study number
        </h4>
          <%= form_for(Patient.new) do |p| %>
          <div class="form-inline" role="form">
              <!--input id="studynumber" name="studynumber" class="form-control" style="width:120px" placeholder="Study number"/-->
              <%= p.text_field :studynumber, style: "width: 120px;" %>
              <%= p.select :country, options_from_collection_for_select(Country.all, :id, :countryname), {include_blank: true}, {class: "form-control", style: "width:100px"} %>
              <%= p.submit "Create", class: "btn btn-primary form-control" %>
          </div>
          <% end %>
        <h4>
          Delete a study number
        </h4>
        <%= form_for(:patient, url: "/patients", html: {method: :delete}) do |p| %>
        <div class="form-inline" role="form">
          <%= p.select :id, options_from_collection_for_select(Patient.all, :id, :studynumber), {include_blank: true}, {class: "form-control", style: "width: 120px;"} %>
          <%= p.submit "Delete", class: "btn btn-danger form-control" %>
        </div>
        <% end %>
        <!--div>
          <%= button_to "Delete swedes", {:controller => :patients, :action => 'destroy', :id => 1 }, {:method => :delete, class: "btn btn-danger" } %>
        </div-->
        <% end %>
      </div>
      <div>
        
      </div>
      <div class="span6" align="center">
        <h2 style="text-align:center">Done</h2>
        <input align="center" placeholder="Search..." ng-model="filterOptionsDone.filterText" style="width:200px;"/>
        <div class="gridStyle" ng-grid="gridOptionsDone"></div>
        Total: {{myDataDone.length}}
        <% if current_user.admin %>
    <p>
    Download CSV:
    <%= link_to "Patients", patients_path(format: "csv") %> | <%= link_to "Journals", journals_path(format: "csv") %> | <%= link_to "Surgeries", surgeries_path(format: "csv") %> | <%= link_to "BoneMarrowTransplantations", bone_marrow_transplantations_path(format: "csv") %> | <%= link_to "ChemoTherapies", chemo_therapies_path(format: "csv") %> | <%= link_to "CytostaticDrugGivens", cytostatic_drug_givens_path(format: "csv") %> | <%= link_to "CytostaticDrugGivenBoneMarrows", cytostatic_drug_given_bone_marrows_path(format: "csv") %>
    </p>
  <% end %> 
      </div>
    </div>
    <div class="row-fluid">
      <br>
      <br>
      <div class="progress span10 offset1">
        <div class="bar" style="width:<%= @progress %>%">
        </div>

      </div>
    </div>
  </div>
</div>

  <% else %>
  
  <%= image_tag "ALiCCS.JPG" %>
  

<!--<div class="center hero-unit">
  <h1>Welcome to the ALiCCS App</h1>

  <h2>
    This is the home page of the ALiCCS journal database.
  </h2>
</div>-->
<h1 style="margin-top:30px">Sign in</h1>

<div class="row">
  <div class="span6 offset3">
    <!--
    <%= form_for(:session, url: sessions_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>
    -->
    <%= form_for("user", :url => user_session_path) do |f| %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in', class: "btn btn-primary" %>
  <%= link_to "Forgot your password?", new_password_path('user') %>
<% end %>
    <p>New user? Please contact Thorgerdur (thorgud@cancer.dk)</p>
  </div>
</div>
  <% end %>