config/routes.rb
SampleApp::Application.routes.draw do
  

  devise_for :admins

  resources :cytostatic_drug_given_bone_marrows

  devise_for :users
  match '/patients', to: 'patients#destroy', via: 'delete'
  resources :patients
  match '/patients/:id/edit_remission', to: 'patients#edit_remission', via: 'get'

  resources :bone_marrow_transplantations
  resources :chemo_therapies
  resources :cytostatic_drug_givens
  resources :cytostatic_drug_given_bone_marrows
  

  resources :users
  resources :journals
  match '/journal/:id/edit_relapse(.:format)', to: 'journal#edit_relapse', via: 'get'
  resources :surgeries

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/form/setcountry', to: 'form#setcountry', via: 'put'

  match '/form/get_journals', to: 'form#get_journals', via: 'get'
  match '/form/:id(:format)', to: 'form#show', via: 'get'

end

app/models/cytostatic_drug_given.rb
class CytostaticDrugGiven < ActiveRecord::Base
  attr_accessible *column_names, :bone_marrow_transplantation_id, :anthracyclinesbolusinf, :anthracyclinesbolusinfnoyes, :chemoorbonemarrow, :cytostaticdrugid, :dosequality, :journal_id, :totalcumulateddosemg, :totalcumulateddoseunits
  belongs_to :journal, dependent: :destroy
  belongs_to :bone_marrow_transplantation, dependent: :destroy

  validates_presence_of :cytostaticdrugid, :totalcumulateddosemg, :dosequality
  validates_presence_of :anthracyclinesbolusinf, :if => :anthracycline?
  def anthracycline?
    [302, 304, 307, 310].include? cytostaticdrugid
  end
  def self.get_values(id)
    row = []
    j = CytostaticDrugGiven.find(id)
    row << j.attributes.values_at(*column_names)
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      columns = ["id", "journal_id", "cytostaticdrugid", "totalcumulateddosemg", "dosequality",
        "anthracyclinesbolusinf", "chemoorbonemarrow"]
      csv << column_names
      all.each do |cytostatic_drug_given|
        csv << cytostatic_drug_given.attributes.values_at(*columns).collect{|item| if item.class == String then item.squish() else item end}
      end
    end
  end
end

app/controllers/cytostatic_drug_givens_controller.rb
class CytostaticDrugGivensController < ApplicationController
  # GET /cytostatic_drug_givens
  # GET /cytostatic_drug_givens.json
  def index
    if request.format == 'csv'
      @cytostatic_drug_givens = CytostaticDrugGiven.order(:id)
    else
      @cytostatic_drug_givens = CytostaticDrugGiven.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cytostatic_drug_givens }
      format.csv { send_data @cytostatic_drug_givens.to_csv({col_sep: "#"}) }
    end
  end

  # GET /cytostatic_drug_givens/1
  # GET /cytostatic_drug_givens/1.json
  def show
    @cytostatic_drug_given = CytostaticDrugGiven.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cytostatic_drug_given }
    end
  end

  # GET /cytostatic_drug_givens/new
  # GET /cytostatic_drug_givens/new.json
  def new
    @cytostatic_drug_given = CytostaticDrugGiven.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cytostatic_drug_given }
    end
  end

  # GET /cytostatic_drug_givens/1/edit
  def edit
    @cytostatic_drug_given = CytostaticDrugGiven.find(params[:id])
  end

  # POST /cytostatic_drug_givens
  # POST /cytostatic_drug_givens.json
  def create
    @cytostatic_drug_given = CytostaticDrugGiven.new(params[:cytostatic_drug_given])

    respond_to do |format|
      if @cytostatic_drug_given.save
        format.html { redirect_to @cytostatic_drug_given, notice: 'Cytostatic drug given was successfully created.' }
        format.json { render json: @cytostatic_drug_given, status: :created, location: @cytostatic_drug_given }
      else
        format.html { render action: "new" }
        format.json { render json: @cytostatic_drug_given.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cytostatic_drug_givens/1
  # PUT /cytostatic_drug_givens/1.json
  def update
    @cytostatic_drug_given = CytostaticDrugGiven.find(params[:id])

    respond_to do |format|
      if @cytostatic_drug_given.update_attributes(params[:cytostatic_drug_given])
        format.html { redirect_to @cytostatic_drug_given, notice: 'Cytostatic drug given was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cytostatic_drug_given.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cytostatic_drug_givens/1
  # DELETE /cytostatic_drug_givens/1.json
  def destroy
    @cytostatic_drug_given = CytostaticDrugGiven.find(params[:id])
    @cytostatic_drug_given.destroy

    respond_to do |format|
      format.html { redirect_to cytostatic_drug_givens_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cytostatic_drug_givens_helper.rb
module CytostaticDrugGivensHelper
end

app/views/cytostatic_drug_givens/_form.html.erb
<%= form_for(@cytostatic_drug_given) do |f| %>
  <% if @cytostatic_drug_given.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cytostatic_drug_given.errors.count, "error") %> prohibited this cytostatic_drug_given from being saved:</h2>

      <ul>
      <% @cytostatic_drug_given.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cytostatic_drug_givens/edit.html.erb
<h1>Editing cytostatic_drug_given</h1>

<%= render 'form' %>

<%= link_to 'Show', @cytostatic_drug_given %> |
<%= link_to 'Back', cytostatic_drug_givens_path %>

app/views/cytostatic_drug_givens/index.html.erb
<h1>Listing cytostatic_drug_givens</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cytostatic_drug_givens.each do |cytostatic_drug_given| %>
  <tr>
    <td><%= link_to 'Show', cytostatic_drug_given %></td>
    <td><%= link_to 'Edit', edit_cytostatic_drug_given_path(cytostatic_drug_given) %></td>
    <td><%= link_to 'Destroy', cytostatic_drug_given, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cytostatic drug given', new_cytostatic_drug_given_path %>

app/views/cytostatic_drug_givens/new.html.erb
<h1>New cytostatic_drug_given</h1>

<%= render 'form' %>

<%= link_to 'Back', cytostatic_drug_givens_path %>

app/views/cytostatic_drug_givens/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_cytostatic_drug_given_path(@cytostatic_drug_given) %> |
<%= link_to 'Back', cytostatic_drug_givens_path %>