config/routes.rb
SampleApp::Application.routes.draw do
  

  devise_for :admins

  resources :cytostatic_drug_given_bone_marrows

  devise_for :users
  match '/patients', to: 'patients#destroy', via: 'delete'
  resources :patients
  match '/patients/:id/edit_remission', to: 'patients#edit_remission', via: 'get'

  resources :bone_marrow_transplantations
  resources :chemo_therapies
  resources :cytostatic_drug_givens
  resources :cytostatic_drug_given_bone_marrows
  

  resources :users
  resources :journals
  match '/journal/:id/edit_relapse(.:format)', to: 'journal#edit_relapse', via: 'get'
  resources :surgeries

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/form/setcountry', to: 'form#setcountry', via: 'put'

  match '/form/get_journals', to: 'form#get_journals', via: 'get'
  match '/form/:id(:format)', to: 'form#show', via: 'get'

end

app/models/bone_marrow_transplantation.rb
class BoneMarrowTransplantation < ActiveRecord::Base
  attr_accessible *column_names, :cytostatic_drug_given_bone_marrow_attributes, :cytostatic_drug_given_attributes, :allogeneic, :autologous, :bodysurfaceconditioning, :chemotherapy, :chemotherapydateofcompletion, :chemotherapydateofinitiation, :completiondate, :cumulativedose, :donor, :heightconditioning, :numberoffractions, :radiotherapyrecordscopied, :journal_id, :source, :startdate, :totalbodyirritation, :transplantationdate, :transplantationnumber, :weightconditioning
  belongs_to :journal, dependent: :destroy
  has_many :cytostatic_drug_given, dependent: :destroy
  has_many :cytostatic_drug_given_bone_marrow, dependent: :destroy
  accepts_nested_attributes_for :cytostatic_drug_given, allow_destroy: true
  accepts_nested_attributes_for :cytostatic_drug_given_bone_marrow, allow_destroy: true

  validates_presence_of :transplantationdate_day, :transplantationdate_month, :transplantationdate_year, :autologous, :allogeneic, :donor, :source, :totalbodyirritation,  :chemotherapy
  validates_presence_of :chemotherapydateofinitiation_day, :chemotherapydateofinitiation_month, :chemotherapydateofinitiation_year, :chemotherapydateofcompletion_day, :chemotherapydateofcompletion_month, :chemotherapydateofcompletion_year, :bodysurfaceconditioning, :weightconditioning, :heightconditioning, :if => :chemo_therapy?



  validates_inclusion_of :transplantationdate_day, :startdate_day, :completiondate_day, :chemotherapydateofinitiation_day, :chemotherapydateofcompletion_day, :in => Array(1..31) + [99] + [nil]
  validates_inclusion_of :transplantationdate_month, :startdate_month, :completiondate_month, :chemotherapydateofinitiation_month, :chemotherapydateofcompletion_month, :in => Array(1..12) + [99] + [nil]
  validates_inclusion_of :transplantationdate_year, :startdate_year, :completiondate_year, :chemotherapydateofinitiation_year, :chemotherapydateofcompletion_year, :in => Array(1970..2100) + [99] + [nil]



  def chemo_therapy?
    chemotherapy == 1
  end
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      columns = ["id", "journal_id", "transplantationdate_day", "transplantationdate_month", "transplantationdate_year",
        "autologous", "allogeneic", "donor", "source", "totalbodyirritation", #"startdate_day", "startdate_month", "startdate_year",
        #"completiondate_day", "completiondate_month", "completiondate_year", "radiotherapyrecordscopied",
        "chemotherapy",
        "chemotherapydateofinitiation_day", "chemotherapydateofinitiation_month", "chemotherapydateofinitiation_year", 
        "chemotherapydateofcompletion_day", "chemotherapydateofcompletion_month", "chemotherapydateofcompletion_year",
        "bodysurfaceconditioning", "weightconditioning", "heightconditioning", "cardioprotectants", "treatmentprotocol"
      ]
      csv << column_names
      all.each do |bone_marrow_transplantation|
        csv << bone_marrow_transplantation.attributes.values_at(*columns).collect{|item| if item.class == String then item.squish() else item end}
      end
    end
  end
end

app/controllers/bone_marrow_transplantations_controller.rb
class BoneMarrowTransplantationsController < ApplicationController
  # GET /bone_marrow_transplantations
  # GET /bone_marrow_transplantations.json
  def index
    if request.format == 'csv'
      @bone_marrow_transplantations = BoneMarrowTransplantation.order(:id)
    else
      @bone_marrow_transplantations = BoneMarrowTransplantation.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bone_marrow_transplantations }
      format.csv { send_data @bone_marrow_transplantations.to_csv({col_sep: "#"}) }
    end
  end

  # GET /bone_marrow_transplantations/1
  # GET /bone_marrow_transplantations/1.json
  def show
    @bone_marrow_transplantation = BoneMarrowTransplantation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bone_marrow_transplantation }
    end
  end

  # GET /bone_marrow_transplantations/new
  # GET /bone_marrow_transplantations/new.json
  def new
    @bone_marrow_transplantation = BoneMarrowTransplantation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bone_marrow_transplantation }
    end
  end

  # GET /bone_marrow_transplantations/1/edit
  def edit
    @bone_marrow_transplantation = BoneMarrowTransplantation.find(params[:id])
  end

  # POST /bone_marrow_transplantations
  # POST /bone_marrow_transplantations.json
  def create
    @bone_marrow_transplantation = BoneMarrowTransplantation.new(params[:bone_marrow_transplantation])

    respond_to do |format|
      if @bone_marrow_transplantation.save
        format.html { redirect_to @bone_marrow_transplantation, notice: 'Bone marrow transplantation was successfully created.' }
        format.json { render json: @bone_marrow_transplantation, status: :created, location: @bone_marrow_transplantation }
      else
        format.html { render action: "new" }
        format.json { render json: @bone_marrow_transplantation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bone_marrow_transplantations/1
  # PUT /bone_marrow_transplantations/1.json
  def update
    @bone_marrow_transplantation = BoneMarrowTransplantation.find(params[:id])

    respond_to do |format|
      if @bone_marrow_transplantation.update_attributes(params[:bone_marrow_transplantation])
        format.html { redirect_to @bone_marrow_transplantation, notice: 'Bone marrow transplantation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bone_marrow_transplantation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bone_marrow_transplantations/1
  # DELETE /bone_marrow_transplantations/1.json
  def destroy
    @bone_marrow_transplantation = BoneMarrowTransplantation.find(params[:id])
    @bone_marrow_transplantation.destroy

    respond_to do |format|
      format.html { redirect_to bone_marrow_transplantations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bone_marrow_transplantations_helper.rb
module BoneMarrowTransplantationsHelper
end

app/views/bone_marrow_transplantations/_form.html.erb
<%= form_for(@bone_marrow_transplantation) do |f| %>
  <% if @bone_marrow_transplantation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bone_marrow_transplantation.errors.count, "error") %> prohibited this bone_marrow_transplantation from being saved:</h2>

      <ul>
      <% @bone_marrow_transplantation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bone_marrow_transplantations/edit.html.erb
<h1>Editing bone_marrow_transplantation</h1>

<%= render 'form' %>

<%= link_to 'Show', @bone_marrow_transplantation %> |
<%= link_to 'Back', bone_marrow_transplantations_path %>

app/views/bone_marrow_transplantations/index.html.erb
<h1>Listing bone_marrow_transplantations</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bone_marrow_transplantations.each do |bone_marrow_transplantation| %>
  <tr>
    <td><%= link_to 'Show', bone_marrow_transplantation %></td>
    <td><%= link_to 'Edit', edit_bone_marrow_transplantation_path(bone_marrow_transplantation) %></td>
    <td><%= link_to 'Destroy', bone_marrow_transplantation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bone marrow transplantation', new_bone_marrow_transplantation_path %>

app/views/bone_marrow_transplantations/new.html.erb
<h1>New bone_marrow_transplantation</h1>

<%= render 'form' %>

<%= link_to 'Back', bone_marrow_transplantations_path %>

app/views/bone_marrow_transplantations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_bone_marrow_transplantation_path(@bone_marrow_transplantation) %> |
<%= link_to 'Back', bone_marrow_transplantations_path %>