config/routes.rb
SampleApp::Application.routes.draw do
  

  devise_for :admins

  resources :cytostatic_drug_given_bone_marrows

  devise_for :users
  match '/patients', to: 'patients#destroy', via: 'delete'
  resources :patients
  match '/patients/:id/edit_remission', to: 'patients#edit_remission', via: 'get'

  resources :bone_marrow_transplantations
  resources :chemo_therapies
  resources :cytostatic_drug_givens
  resources :cytostatic_drug_given_bone_marrows
  

  resources :users
  resources :journals
  match '/journal/:id/edit_relapse(.:format)', to: 'journal#edit_relapse', via: 'get'
  resources :surgeries

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/form/setcountry', to: 'form#setcountry', via: 'put'

  match '/form/get_journals', to: 'form#get_journals', via: 'get'
  match '/form/:id(:format)', to: 'form#show', via: 'get'

end

app/models/chemo_therapy.rb
class ChemoTherapy < ActiveRecord::Base
  attr_accessible *column_names, :treatmentprotocol, :bodysurface, :height, :measurementdate, :journal_id, :weight, :yearnumber, :estimated
  belongs_to :journal, dependent: :destroy

  validates_presence_of :bodysurface, :measurementdate_day, :measurementdate_month, :measurementdate_year, :weight, :height, :estimated
  def self.get_values(id)
    row = []
    j = ChemoTherapy.find(id)
    row << j.attributes.values_at(*column_names)
  end
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      columns = ["id", "journal_id", "bodysurface", "measurementdate_day", "measurementdate_month", "measurementdate_year",
        "weight", "height", "estimated"]
      csv << column_names
      all.each do |chemo_therapies|
        csv << chemo_therapies.attributes.values_at(*columns).collect{|item| if item.class == String then item.squish() else item end}
      end
    end
  end
end

app/controllers/chemo_therapies_controller.rb
class ChemoTherapiesController < ApplicationController
  # GET /chemo_therapies
  # GET /chemo_therapies.json
  def index
    if request.format == 'csv'
      @chemo_therapies = ChemoTherapy.order(:id)
    else
      @chemo_therapies = ChemoTherapy.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chemo_therapies }
      format.csv {send_data @chemo_therapies.to_csv({col_sep: "#"}) }
    end
  end

  # GET /chemo_therapies/1
  # GET /chemo_therapies/1.json
  def show
    @chemo_therapy = ChemoTherapy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chemo_therapy }
    end
  end

  # GET /chemo_therapies/new
  # GET /chemo_therapies/new.json
  def new
    @chemo_therapy = ChemoTherapy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chemo_therapy }
    end
  end

  # GET /chemo_therapies/1/edit
  def edit
    @chemo_therapy = ChemoTherapy.find(params[:id])
  end

  # POST /chemo_therapies
  # POST /chemo_therapies.json
  def create
    @chemo_therapy = ChemoTherapy.new(params[:chemo_therapy])

    respond_to do |format|
      if @chemo_therapy.save
        format.html { redirect_to @chemo_therapy, notice: 'Chemo therapy was successfully created.' }
        format.json { render json: @chemo_therapy, status: :created, location: @chemo_therapy }
      else
        format.html { render action: "new" }
        format.json { render json: @chemo_therapy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chemo_therapies/1
  # PUT /chemo_therapies/1.json
  def update
    @chemo_therapy = ChemoTherapy.find(params[:id])

    respond_to do |format|
      if @chemo_therapy.update_attributes(params[:chemo_therapy])
        format.html { redirect_to @chemo_therapy, notice: 'Chemo therapy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chemo_therapy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chemo_therapies/1
  # DELETE /chemo_therapies/1.json
  def destroy
    @chemo_therapy = ChemoTherapy.find(params[:id])
    @chemo_therapy.destroy

    respond_to do |format|
      format.html { redirect_to chemo_therapies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/chemo_therapies_helper.rb
module ChemoTherapiesHelper
end

app/views/chemo_therapies/_form.html.erb
<%= form_for(@chemo_therapy) do |f| %>
  <% if @chemo_therapy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chemo_therapy.errors.count, "error") %> prohibited this chemo_therapy from being saved:</h2>

      <ul>
      <% @chemo_therapy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chemo_therapies/edit.html.erb
<h1>Editing chemo_therapy</h1>

<%= render 'form' %>

<%= link_to 'Show', @chemo_therapy %> |
<%= link_to 'Back', chemo_therapies_path %>

app/views/chemo_therapies/index.html.erb
<h1>Listing chemo_therapies</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chemo_therapies.each do |chemo_therapy| %>
  <tr>
    <td><%= link_to 'Show', chemo_therapy %></td>
    <td><%= link_to 'Edit', edit_chemo_therapy_path(chemo_therapy) %></td>
    <td><%= link_to 'Destroy', chemo_therapy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chemo therapy', new_chemo_therapy_path %>

app/views/chemo_therapies/new.html.erb
<h1>New chemo_therapy</h1>

<%= render 'form' %>

<%= link_to 'Back', chemo_therapies_path %>

app/views/chemo_therapies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_chemo_therapy_path(@chemo_therapy) %> |
<%= link_to 'Back', chemo_therapies_path %>